# Generated by Django 4.2.2 on 2023-07-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_email_contact_subject_contact_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
